user_index:
    pattern:  /
    defaults: { _controller: FileDUserBundle:Security:login }
    
user_inscription:
    pattern:  /inscription
    defaults: { _controller: FileDUserBundle:Registration:register }

user_reset_pwd:
    pattern:  /reset-password
    defaults: { _controller: FileDUserBundle:Resetting:reset }
    
user_profile:
    pattern: /profile/
    defaults: { _controller: FileDUserBundle:Profile:show }
    
user_profile_edit:
    pattern: /profile/edit
    defaults: { _controller: FileDUserBundle:Profile:edit }
    
file_create:
    pattern:  /file/new
    defaults: { _controller: FileDFileBundle:File:new }
    
file_add_file:
    pattern:  /add-file
    defaults: { _controller: FileDFileBundle:File:addfile }
    
file_add_file_server:
    pattern:  /add-file-server
    defaults: { _controller: FileDFileBundle:File:addfileserver }
    
file_add_repository:
    pattern:  /add-repository
    defaults: { _controller: FileDFileBundle:File:addrepository }
    
file_edit:
    pattern:  /edit
    defaults: { _controller: FileDFileBundle:File:edit }
    
file_delete:
    pattern:  /delete
    defaults: { _controller: FileDFileBundle:File:delete }
    
file_download:
    pattern:  /file/{id}/download
    defaults: { _controller: FileDFileBundle:File:download }
    
file_share:
    pattern:  /share
    defaults: { _controller: FileDFileBundle:File:shareFile }
    
file_mark_as_seen:
    pattern:  /mark
    defaults: { _controller: FileDFileBundle:File:markAsSeen }
    
file_refresh:
    pattern:  /refresh
    defaults: { _controller: FileDFileBundle:File:refresh }
    
file_public_link:
    pattern: /file/{hash}
    defaults: { _controller: FileDFileBundle:File:publicLink }
    
file_download_public:
    pattern:  /public/download/{id}
    defaults: { _controller: FileDFileBundle:File:downloadPublic }
    
    