user_index:
    pattern:  /
    defaults: { _controller: FileDUserBundle:User:index }
    
user_inscription:
    pattern:  /inscription
    defaults: { _controller: FileDUserBundle:Registration:register }
