parameters:
#    file_d_user.example.class: FileD\UserBundle\Example

services:
#    file_d_user.example:
#        class: %file_d_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
